# Generated by Django 5.0.4 on 2024-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cor', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('possui_os_20_dedos', models.BooleanField(default=True)),
            ],
        ),
    ]
