# Generated by Django 5.0.4 on 2024-04-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
